# Generated by Django 4.0.4 on 2022-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contacto_mensaje_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
