# Generated by Django 4.0.4 on 2022-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trabajo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
