# Generated by Django 4.0.4 on 2022-06-08 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_categoria_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mensaje'),
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=200, verbose_name='Diagnostico')),
                ('mecanico', models.CharField(max_length=50, verbose_name='Mecanico')),
                ('fecha', models.DateField(max_length=9, verbose_name='Fecha')),
                ('materiales', models.CharField(max_length=200, verbose_name='Materiales')),
                ('img', models.ImageField(upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
    ]
